"""The published page must agree with the measurements it claims to report.

This project has now published four wrong numbers on three surfaces:

  * a synthetic hit@5 of 86.7% that outlived the corpus it was measured on,
  * a registry count reading "seven" when the registry held eight,
  * and -- in the very session that corrected those two -- a set of retrieval
    figures measured against LIVE stores, published to a README and two live
    sites, then invalidated hours later when the corpus was frozen.

Every one of them was prose. Prose does not fail a build, so nothing noticed.

docs/index.html is generated by docs/build_page.py from evals/runs/page_data.json,
and this test asserts the committed page still matches. Regenerating is the fix
when it fails: re-run the eval, re-run the build, commit both. What must not
happen is the page and the measurement disagreeing quietly, which is the only
failure mode that has actually bitten.
"""

import importlib.util
import json
import re
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).parent.parent
DOCS = REPO / "docs"
PAGE = DOCS / "index.html"
EVAL_JSON = REPO / "evals" / "runs" / "page_data.json"


def _builder():
    spec = importlib.util.spec_from_file_location(
        "_ck_page_builder", DOCS / "build_page.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def page():
    if not PAGE.exists():
        pytest.skip("docs/index.html not built")
    return PAGE.read_text(encoding="utf-8")


class TestPageIsGenerated:
    def test_page_matches_a_fresh_build(self, page, tmp_path, monkeypatch):
        """Byte-identical to what build_page.py produces right now.

        The eval JSON is committed alongside, so this is deterministic. A diff
        means either the measurement moved and the page was not rebuilt, or the
        page was hand-edited -- both of which are the thing this guards.
        """
        if not EVAL_JSON.exists():
            pytest.skip("evals/runs/page_data.json not committed")
        mod = _builder()
        out = tmp_path / "index.html"
        monkeypatch.setattr(mod, "OUT", str(out))
        mod.build()
        assert out.read_text(encoding="utf-8") == page, (
            "docs/index.html is stale. Re-run:\n"
            "  python evals/run_retrieval_eval.py --json evals/runs/page_data.json\n"
            "  python docs/build_page.py")

    def test_no_handwritten_percentages_in_the_template(self):
        """The template must not carry a retrieval figure of its own.

        A number literal in the HTML template is exactly how the last four
        stale claims happened: it survives every corpus change, because nothing
        recomputes it. Percentages must arrive through .format() from measured
        data. (Chart-independent copy like the 100%-confabulation finding and
        the 53%/25% comparison figures are allowlisted -- they cite dated
        measurements from other scripts, named in the prose.)
        """
        src = (DOCS / "build_page.py").read_text(encoding="utf-8")
        template = src.split('PAGE = """', 1)[1]
        allowed = {"100%", "53%", "25%", "20%", "97.3%", "94.1%", "85.5%", "73.3%"}
        found = set(re.findall(r"\b\d{1,3}(?:\.\d+)?%", template)) - allowed
        # CSS widths are fine; strip anything inside a style attribute or block.
        css_free = re.sub(r"(?s)<style>.*?</style>|style=\"[^\"]*\"", "", template)
        found &= set(re.findall(r"\b\d{1,3}(?:\.\d+)?%", css_free))
        assert not found, (
            f"hard-coded retrieval percentages in the page template: {sorted(found)}. "
            "Pass them through from the measurement instead.")


class TestPageAgreesWithTheEval:
    @pytest.fixture(scope="class")
    def measured(self):
        if not EVAL_JSON.exists():
            pytest.skip("evals/runs/page_data.json not committed")
        return json.loads(EVAL_JSON.read_text(encoding="utf-8"))

    def test_headline_recall_appears_verbatim(self, page, measured):
        """The two numbers a reader will quote back at you."""
        for arm in ("lexical", "embedding"):
            pct = round(measured["arms"][arm]["overall"]["recall@5"] * 100)
            assert f">{pct}%<" in page, (
                f"{arm} recall@5 of {pct}% is not on the page")

    def test_case_counts_match(self, page, measured):
        rows = measured["arms"]["lexical"]["rows"]
        assert f"{len(rows)} questions" in page
        for label, kind in (("with a known answer", "positive"),
                            ("deliberately", "negative"),
                            ("superseded history", "history")):
            n = sum(1 for r in rows if r["case_type"] == kind)
            assert f"{n} " in page, f"{kind} count {n} missing near '{label}'"

    def test_the_honest_limits_are_still_stated(self, page):
        """The page's credibility rests on publishing what it does badly.

        If a future edit quietly drops the auto-extraction gap, the abstention
        false-positive rate, or the self-submitted caveat on the comparison,
        the page stops being a measurement and becomes marketing.
        """
        for claim in ("no auto-extraction",
                      "submitted by this project's author",
                      "known-hard problem",
                      "Nothing is captured\n  unless the agent records it"):
            assert claim.replace("\n  ", " ") in page.replace("\n  ", " "), \
                f"the page no longer admits: {claim!r}"

    def test_frozen_corpus_is_named(self, page):
        """Numbers measured against live stores are what broke last time."""
        assert "frozen corpus" in page
